import * as React from "react";
import Head from "next/head";


const PageHead = () => {
    return <Head>
        <title>DoDo 创作者平台</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>;
};
export default PageHead;
